BeforeAll {
    $repositoryRoot = Split-Path $PSScriptRoot -Parent
    $buildScript = Join-Path $repositoryRoot 'Build/Build-Module.ps1'
    $outputPath = Join-Path $TestDrive 'Build'
    $originalManifestHash = (Get-FileHash -LiteralPath (Join-Path $repositoryRoot 'PX2PS.psd1')).Hash
    $buildOutput = & pwsh -NoLogo -NoProfile -File $buildScript -CalVer '2026.10.41234' -Prerelease 'pre' -OutputPath $outputPath 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Build failed: $($buildOutput -join [Environment]::NewLine)"
    }
    $artifactPath = Join-Path $outputPath 'Unpacked/PX2PS'
    $manifestPath = Join-Path $artifactPath 'PX2PS.psd1'
    $manifest = Import-PowerShellDataFile -Path $manifestPath
}

Describe 'PX2PS release build' {
    It 'builds the requested CalVer and prerelease metadata' {
        $manifest.ModuleVersion | Should -BeExactly '2026.10.41234'
        $manifest.PrivateData.PSData.Prerelease | Should -BeExactly 'pre'
    }

    It 'leaves the source manifest and module unchanged' {
        (Get-FileHash -LiteralPath (Join-Path $repositoryRoot 'PX2PS.psd1')).Hash | Should -BeExactly $originalManifestHash
        (Get-FileHash -LiteralPath (Join-Path $artifactPath 'PX2PS.psm1')).Hash |
            Should -BeExactly (Get-FileHash -LiteralPath (Join-Path $repositoryRoot 'PX2PS.psm1')).Hash
    }

    It 'ships an importable module with the same rendered output and alias' {
        $imagePath = Join-Path $repositoryRoot 'Examples/PixquareLogo.px'
        Import-Module -Name (Join-Path $repositoryRoot 'PX2PS.psd1') -Force
        $expected = @(Convert-PX2PS -Path $imagePath -RenderMode VT 6>&1 | ForEach-Object { [string]$_ })
        $builtModule = Import-Module -Name $manifestPath -Force -PassThru
        $builtModule.Version.ToString() | Should -BeExactly '2026.10.41234'
        (Get-Alias -Name px2ps).Definition | Should -BeExactly 'Convert-PX2PS'
        $actual = @(px2ps -Path $imagePath -RenderMode VT 6>&1 | ForEach-Object { [string]$_ })
        $actual.Count | Should -Be $expected.Count
        for ($index = 0; $index -lt $expected.Count; $index++) {
            $actual[$index] | Should -BeExactly $expected[$index]
        }
        $generatedPath = Join-Path $TestDrive 'Generated.ps1'
        px2ps -Path $imagePath -OutputMode Script -OutputPath $generatedPath
        (Get-Content -LiteralPath $generatedPath)[1] | Should -BeExactly '# Auto-generated by PX2PS 2026.10.41234'
        Remove-Module -Name PX2PS
    }

    It 'builds a stable artifact without carrying over prerelease metadata' {
        $buildOutput = & pwsh -NoLogo -NoProfile -File $buildScript -CalVer '2026.10.41235' -OutputPath $outputPath 2>&1
        $LASTEXITCODE | Should -Be 0 -Because ($buildOutput -join [Environment]::NewLine)
        $stableManifest = Import-PowerShellDataFile -Path $manifestPath
        $stableManifest.ModuleVersion | Should -BeExactly '2026.10.41235'
        $stableManifest.PrivateData.PSData.Prerelease | Should -BeNullOrEmpty
    }
}
