BeforeAll {
    $modulePath = Join-Path $PSScriptRoot '../PX2PS.psd1'
    $module = Import-Module -Name $modulePath -Force -PassThru
    $imagePath = Join-Path $PSScriptRoot '../Examples/PixquareLogo.px'
    $outputPath = Join-Path $TestDrive 'PixquareLogo.ps1'
    $generationStart = Get-Date
    Convert-PX2PS -Path $imagePath -OutputMode Script -OutputPath $outputPath -RenderMode VT
    $generationEnd = Get-Date
    $scriptLines = Get-Content -LiteralPath $outputPath
}

Describe 'Convert-PX2PS generated scripts' {
    It 'records the loaded module version in the header' {
        $scriptLines[1] | Should -BeExactly "# Auto-generated by PX2PS $($module.Version)"
    }

    It 'records the actual generation time separately from the module version' {
        $scriptLines[3] | Should -Match '^# Generated: \d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$'
        $generatedAt = [datetime]::ParseExact(
            $scriptLines[3].Substring('# Generated: '.Length),
            'yyyy-MM-dd HH:mm:ss',
            [System.Globalization.CultureInfo]::InvariantCulture
        )
        $generatedAt | Should -BeGreaterOrEqual $generationStart.AddSeconds(-1)
        $generatedAt | Should -BeLessOrEqual $generationEnd
    }

    It 'renders the same image as direct display' {
        $expected = @(Convert-PX2PS -Path $imagePath -RenderMode VT 6>&1 |
            ForEach-Object { [string]$_ })
        $actual = @(& $outputPath 6>&1 | ForEach-Object { [string]$_ })
        $actual.Count | Should -Be $expected.Count
        for ($index = 0; $index -lt $expected.Count; $index++) {
            $actual[$index] | Should -BeExactly $expected[$index]
        }
    }
}
